- name: Patch for Linuc
  hosts: localhost
  become: true
  tasks:
    - name: Linux Block
      when: ansible_os_family in ["RedHat", "Debian"]
      block:
        - name: Apply updates using DNF
          ansible.builtin.dnf:
            name: 'nginx'
            state: latest
          when: ansible_os_family == "RedHat"
