- name: Patch for Linux
  hosts: localhost
  become: true
  tasks:
    - name: Linux Block
      when: ansible_os_family in ["RedHat", "Debian"]
      block:
        - name: Run yum update via shell
          ansible.builtin.shell: yum update nginx
