- name: Post-flight for Linux
  hosts: localhost
  tasks:
    - name: Linux Block
      when: ansible_os_family in ["RedHat", "Debian"]
      block:
        - name: Register python
          ansible.builtin.shell: pip3 show pip
          register: pv
        - name: Distribution major version
          debug: v.stdout_lines
        - name: Try setfacts
          ansible.builtin.set_fact: 
          pversion: pv.stdout_lines
