- name: Post-flight for Linux
  hosts: localhost
  become: true
  tasks:
    - name: Linux Block
      when: ansible_os_family in ["RedHat", "Debian"]
      block:
        - name: check version
          ansible.builtin.shell: pycurl --version
          register: vs
        - name: Distribution major version
          debug: var=vs.stdout_lines
