- name: Post-flight for Linux
  hosts: localhost
  tasks:
    - name: Linux Block
      when: ansible_os_family in ["RedHat", "Debian"]
      block:
        - name: pwd 
          ansible.builtin.shell: pwd
        - name: who
          ansible.builtin.shell: who
        - name: check patchfile
          ansible.builtin.shell: pip3 show pip
          register: pv
        - name: Distribution major version
          debug: var=pv.stdout_lines
