- name: Patch for Linux
  hosts: localhost
  become: true
  tasks:
    - name: Linux Block
      when: ansible_os_family in ["RedHat", "Debian"]
      block:
        - name: Rollback pip
          ansible.builtin.shell: pip3 install pip==26.1.2 --ignore-installed
